# Generated by Django 5.1.9 on 2025-05-25 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=50)),
                ('objective', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('audience_segment', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('date_detected', models.DateField()),
                ('severity', models.CharField(max_length=20)),
                ('metric_affected', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.campaign')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'db_table': 'analysis_results',
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('conversions', models.IntegerField()),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ctr', models.FloatField()),
                ('cpc', models.FloatField()),
                ('cpa', models.FloatField()),
                ('roas', models.FloatField()),
                ('device_breakdown', models.JSONField()),
                ('geography', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.campaign')),
            ],
            options={
                'verbose_name': 'Daily Metric',
                'verbose_name_plural': 'Daily Metrics',
                'db_table': 'daily_metrics',
            },
        ),
    ]
